<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="LibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book">
      <Column Name="BookId" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Author" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Publisher" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Category" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Available" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Book_Event_BookAcquisition" Member="Event_BookAcquisitions" ThisKey="BookId" OtherKey="BookId" Type="Event_BookAcquisition" />
      <Association Name="Book_Event_BookDeletion" Member="Event_BookDeletions" ThisKey="BookId" OtherKey="BookId" Type="Event_BookDeletion" />
      <Association Name="Book_Event_RentsReturn" Member="Event_RentsReturns" ThisKey="BookId" OtherKey="BookId" Type="Event_RentsReturn" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Surname" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Address" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PhoneNumber" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Employee_Event_BookAcquisition" Member="Event_BookAcquisitions" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="Event_BookAcquisition" />
      <Association Name="Employee_Event_BookDeletion" Member="Event_BookDeletions" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="Event_BookDeletion" />
      <Association Name="Employee_Event_RentsReturn" Member="Event_RentsReturns" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="Event_RentsReturn" />
    </Type>
  </Table>
  <Table Name="dbo.Event_BookAcquisitions" Member="Event_BookAcquisitions">
    <Type Name="Event_BookAcquisition">
      <Column Name="AcquisitionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookId" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReaderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupplierId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Book_Event_BookAcquisition" Member="Book" ThisKey="BookId" OtherKey="BookId" Type="Book" IsForeignKey="true" />
      <Association Name="Employee_Event_BookAcquisition" Member="Employee" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="Employee" IsForeignKey="true" />
      <Association Name="Reader_Event_BookAcquisition" Member="Reader" ThisKey="ReaderId" OtherKey="ReaderId" Type="Reader" IsForeignKey="true" />
      <Association Name="Supplier_Event_BookAcquisition" Member="Supplier" ThisKey="SupplierId" OtherKey="SupplierId" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event_BookDeletions" Member="Event_BookDeletions">
    <Type Name="Event_BookDeletion">
      <Column Name="BookDeletionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookId" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Book_Event_BookDeletion" Member="Book" ThisKey="BookId" OtherKey="BookId" Type="Book" IsForeignKey="true" />
      <Association Name="Employee_Event_BookDeletion" Member="Employee" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event_RentsReturns" Member="Event_RentsReturns">
    <Type Name="Event_RentsReturn">
      <Column Name="RentReturnId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookId" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReaderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Rent/Return]" Member="Rent_Return" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Book_Event_RentsReturn" Member="Book" ThisKey="BookId" OtherKey="BookId" Type="Book" IsForeignKey="true" />
      <Association Name="Employee_Event_RentsReturn" Member="Employee" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="Employee" IsForeignKey="true" />
      <Association Name="Reader_Event_RentsReturn" Member="Reader" ThisKey="ReaderId" OtherKey="ReaderId" Type="Reader" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Readers" Member="Readers">
    <Type Name="Reader">
      <Column Name="ReaderId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Surname" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Address" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PhoneNumber" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Reader_Event_BookAcquisition" Member="Event_BookAcquisitions" ThisKey="ReaderId" OtherKey="ReaderId" Type="Event_BookAcquisition" />
      <Association Name="Reader_Event_RentsReturn" Member="Event_RentsReturns" ThisKey="ReaderId" OtherKey="ReaderId" Type="Event_RentsReturn" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Address" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PhoneNumber" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Supplier_Event_BookAcquisition" Member="Event_BookAcquisitions" ThisKey="SupplierId" OtherKey="SupplierId" Type="Event_BookAcquisition" />
    </Type>
  </Table>
</Database>